server.address=127.0.0.1
management.endpoints.web.exposure.include=health,configprops
management.endpoint.configprops.show-values=always
app.languages=QUESTION,ANSWER
app.question-language=QUESTION
app.answer-language=ANSWER