package org.igye.remem3.app.controllers.cardimporter;

import lombok.RequiredArgsConstructor;
import org.apache.commons.lang3.StringUtils;
import org.igye.remem3.app.controllers.cardexplorer.CardExplorerConstructor;
import org.igye.remem3.app.imprt.CardCollectionDto;
import org.igye.remem3.app.state.StateRenderer;
import org.igye.remem3.html.HtmlBuilder;
import org.igye.remem3.html.HtmlElem;
import org.igye.remem3.html.HtmlTag;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

@RequiredArgsConstructor
public class CardImporterRenderer extends HtmlBuilder implements StateRenderer<CardImporterState> {
    public static final String PAR_DIR = "CardImporter_PAR_DIR";
    public static final String PAR_FILE = "CardImporter_PAR_FILE";
    public static final String PAR_JSON_TEXT = "CardImporter_PAR_JSON_TEXT";
    public static final String PAR_ROOT_CHAPTER_NAME = "CardImporter_PAR_ROOT_CHAPTER_NAME";
    public static final String PAR_SKIP_ROOT_DIR = "CardImporter_PAR_SKIP_ROOT_DIR";
    public static final String ACT_LOAD = "CardImporter_ACT_LOAD";
    public static final String ACT_APPLY = "CardImporter_ACT_APPLY";
    public static final String ACT_IMPORT = "CardImporter_ACT_IMPORT";
    public static final String ACT_CLEAR = "CardImporter_ACT_CLEAR";

    private final CardExplorerConstructor cardExplorerConstructor;

    @Override
    public HtmlElem render(CardImporterState st) {
        return simplePageWithTitle("Card importer",
            h4(text("Card importer")),
            rndImportResult(st),
            multipartForm(
                table(List.of(List.of(
                    text("Base directory"),
                    st.getDir().render()
                ))),
                rndLoadControls(st),
                st.getCollection().isPresent() ? rndPreview(st) : rndErrors(st.getErrors())
            )
        );
    }

    private HtmlElem rndImportResult(CardImporterState st) {
        return st.getImportResult()
            .map(res -> div("color:green;",
                text("%s created in %s".formatted(rndNumOfCards(res.getNumOfCreatedCards()), res.getDir())),
                text(" "),
                a(cardExplorerConstructor.makeUrlWithInitPath(res.getDir().getAbsolutePath()), text("Open cards"))
                    .attr("target", "_blank")
            ))
            .orElse(null);
    }

    private HtmlElem rndLoadControls(CardImporterState st) {
        return table(List.of(
            List.of(
                text("JSON file"),
                inpFile(PAR_FILE)
                    .attr("accept", ".json,application/json")
                    .attr("onchange", "clickBtn('%s')".formatted(ACT_LOAD))
            ),
            List.of(
                text("or JSON text"),
                textarea(PAR_JSON_TEXT, st.getJsonText(), 100, 5)
            ),
            List.of(
                text(""),
                inpSubmit(ACT_LOAD, "Load")
            )
        )).attr("class", "table-no-border vertical-align-top");
    }

    private HtmlElem rndPreview(CardImporterState st) {
        CardCollectionDto collection = st.getCollection().get();
        long numOfCards = st.getChapterTree().map(ChapterView::getTotalNumOfCards).orElse(0L);
        HtmlTag importBtn = inpSubmit(ACT_IMPORT, "Import %s".formatted(rndNumOfCards(numOfCards)));
        if (!st.getErrors().isEmpty()) {
            importBtn = importBtn.disabled();
        }
        return frag(
            hr(),
            div(text(
                "Loaded from %s%s.".formatted(
                    st.getSource(),
                    StringUtils.isBlank(collection.getGeneratedBy())
                        ? ""
                        : ", generated by %s".formatted(collection.getGeneratedBy())
                )
            )),
            rndErrors(st.getErrors()),
            table(List.of(
                List.of(
                    text("Root chapter name"),
                    inpText(PAR_ROOT_CHAPTER_NAME, st.getRootChapterName(), ACT_APPLY).attr("size", "60"),
                    inpSubmit(ACT_APPLY, "Apply")
                ),
                List.of(
                    text("Skip root directory"),
                    frag(
                        inpCheckbox(PAR_SKIP_ROOT_DIR, PAR_SKIP_ROOT_DIR, st.isSkipRootDir()).submitOnChange(),
                        span("color:grey;", text(
                            "child chapters become direct subdirectories of the base directory"
                        ))
                    )
                )
            )),
            st.getChapterTree().map(root -> ul(List.of(rndChapter(st, root)))).orElse(null),
            div(
                importBtn,
                inpSubmit(ACT_CLEAR, "Clear")
            )
        );
    }

    private HtmlElem rndChapter(CardImporterState st, ChapterView chapter) {
        List<HtmlElem> content = new ArrayList<>();
        content.add(span("font-weight:bold;", text(chapter.getChapterName())));
        content.add(text(" "));
        content.add(rndChapterDir(st, chapter));
        content.add(text(" "));
        content.add(rndCardCounts(chapter));
        if (!chapter.getChapters().isEmpty()) {
            content.add(ul(chapter.getChapters().stream().map(subChapter -> rndChapter(st, subChapter)).toList()));
        }
        return frag(content);
    }

    private HtmlElem rndChapterDir(CardImporterState st, ChapterView chapter) {
        if (chapter.isDirSkipped()) {
            return span("color:grey;", text(
                "[no directory, cards go to %s]".formatted(st.getDir().getSelectedDirectoryStr())
            ));
        }
        if (chapter.getDirError() != null) {
            return span("color:red;", text("[invalid directory name: %s]".formatted(chapter.getDirError())));
        }
        return frag(
            chapter.getDirName().equals(chapter.getChapterName())
                ? null
                : frag(text("→ %s".formatted(chapter.getDirName())), text(" ")),
            chapter.isDirExists()
                ? span("color:orange;", text("[existing directory]"))
                : span("color:green;", text("[new directory]"))
        );
    }

    private HtmlElem rndCardCounts(ChapterView chapter) {
        if (chapter.getCardCounts().isEmpty()) {
            return span("color:grey;", text("no cards"));
        }
        return text(
            chapter.getCardCounts().entrySet().stream()
                .map(typeAndCount -> "%s: %s".formatted(typeAndCount.getKey(), typeAndCount.getValue()))
                .collect(Collectors.joining(", "))
        );
    }

    private String rndNumOfCards(long numOfCards) {
        return numOfCards == 1 ? "1 card" : "%s cards".formatted(numOfCards);
    }
}
