package org.igye.remem3.utils.sqlite.impl;

import org.igye.remem3.app.dbentity.LangEnt;
import org.igye.remem3.app.impl.DbSchemaImpl;
import org.igye.remem3.utils.sqlite.Database;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.List;

class TransactionImplTest {
    @Test
    void insert_sets_autogenerated_ids() {
        //given
        Database db = DatabaseImpl.getInMemoryDb();
        DbSchemaImpl sc = new DbSchemaImpl();
        db.transactionV(sc::upgrade);
        List<LangEnt> langs = List.of(
            LangEnt.builder().name("L1").build(),
            LangEnt.builder().name("L2").build(),
            LangEnt.builder().name("L3").build()
        );

        //when
        db.transactionV(tx -> tx.insertMany(sc.getLanguageTable(), langs));

        //then
        Assertions.assertEquals(1, langs.get(0).id);
        Assertions.assertEquals(2, langs.get(1).id);
        Assertions.assertEquals(3, langs.get(2).id);
    }
}