package org.igye.remem3.utils.sqlite.impl;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.SneakyThrows;
import org.igye.remem3.app.db.DbSchema;
import org.igye.remem3.app.db.entities.CardEnt;
import org.igye.remem3.app.db.entities.CardHistEnt;
import org.igye.remem3.app.db.entities.CardTypeEnt;
import org.igye.remem3.app.db.entities.FolderEnt;
import org.igye.remem3.app.db.entities.LangEnt;
import org.igye.remem3.app.db.impl.DbSchemaImpl;
import org.igye.remem3.utils.Exn;
import org.igye.remem3.utils.sqlite.Column;
import org.igye.remem3.utils.sqlite.Database;
import org.igye.remem3.utils.sqlite.Table;
import org.junit.jupiter.api.Test;

import java.time.Instant;
import java.util.List;

import static org.igye.remem3.app.db.impl.DbSchemaImpl.LANG_NAME;
import static org.igye.remem3.utils.sqlite.ColumnType.TEXT;
import static org.igye.remem3.utils.sqlite.Table.HIST_ID;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class TransactionImplTest {
    @Test
    void insert_sets_autogenerated_ids() {
        //given
        DbSchema sc = new DbSchemaImpl();
        Database db = DatabaseImpl.getInMemoryDb(sc);
        db.transactionV(sc::upgrade);
        List<LangEnt> langs = List.of(
            LangEnt.builder().name("L1").build(),
            LangEnt.builder().name("L2").build(),
            LangEnt.builder().name("L3").build()
        );

        //when
        db.transactionV(tx -> tx.insertMany(sc.getLanguageTable(), langs));

        //then
        assertEquals(1, langs.get(0).id);
        assertEquals(2, langs.get(1).id);
        assertEquals(3, langs.get(2).id);
    }

    @Test
    void select() {
        //given
        DbSchema sc = new DbSchemaImpl();
        Database db = DatabaseImpl.getInMemoryDb(sc);
        db.transactionV(sc::upgrade);
        db.transactionV(tx -> tx.insertMany(
            sc.getLanguageTable(),
            List.of(
                LangEnt.builder().name("L1").build(),
                LangEnt.builder().name("L2").build(),
                LangEnt.builder().name("L3").build()
            )
        ));

        //when
        List<LangEnt> langs = db.transaction(tx ->
            tx.select(LangEnt.class, sc.getLanguageTable(), null, List.of(LANG_NAME), null)
        );

        //then
        assertEquals(1, langs.get(0).id);
        assertEquals(2, langs.get(1).id);
        assertEquals(3, langs.get(2).id);
    }

    @SneakyThrows
    @Test
    void test_history() {
        //given
        DbSchema sc = new DbSchemaImpl();
        Database db = DatabaseImpl.getInMemoryDb(sc);
        db.transactionV(sc::upgrade);
        FolderEnt folder1 = FolderEnt.builder().name("F1").build();
        db.insert(sc.getFolderTable(), folder1);
        FolderEnt folder2 = FolderEnt.builder().name("F1").build();
        db.insert(sc.getFolderTable(), folder2);
        CardTypeEnt cardType1 = CardTypeEnt.builder().code("C1").tableName("T2").build();
        db.insert(sc.getCardTypeTable(), cardType1);
        CardTypeEnt cardType2 = CardTypeEnt.builder().code("C3").tableName("T4").build();
        db.insert(sc.getCardTypeTable(), cardType2);
        assertEquals(0, countRows(db, sc.getCardTable()));
        assertEquals(0, countRows(db, sc.getCardTable().getHistTable()));
        CardEnt card = CardEnt.builder().folderId(folder1.id).cardTypeId(cardType1.id).build();

        //when
        //first insert
        db.insert(sc.getCardTable(), card);

        //then
        assertEquals(1, countRows(db, sc.getCardTable()));
        assertEquals(1, countRows(db, sc.getCardTable().getHistTable()));
        CardEnt cardInDb = db.selectSingleById(CardEnt.class, sc.getCardTable(), card.id);
        assertEquals(card, cardInDb);
        assertEquals(folder1.id, cardInDb.folderId);
        assertEquals(cardType1.id, cardInDb.cardTypeId);
        List<CardHistEnt> cardHist = db.select(
            CardHistEnt.class, sc.getCardTable().getHistTable(), null, List.of(HIST_ID), null
        );
        CardHistEnt cardHistRec0 = cardHist.get(0);
        assertEquals(0, cardHistRec0._act);
        Long histTime0 = cardHistRec0._time;
        assertCurrentTime(histTime0);
        assertEquals(card.id, cardHistRec0.id);
        assertEquals(folder1.id, cardHistRec0.folderId);
        assertEquals(cardType1.id, cardHistRec0.cardTypeId);
        assertEquals(card.crtTime, cardHistRec0.crtTime);

        //when
        //update the first column
        //waiting to change the timestamp in history
        Thread.sleep(10);
        card.folderId = folder2.id;
        db.update(sc.getCardTable(), card);

        //then
        assertEquals(1, countRows(db, sc.getCardTable()));
        assertEquals(2, countRows(db, sc.getCardTable().getHistTable()));
        cardInDb = db.selectSingleById(CardEnt.class, sc.getCardTable(), card.id);
        assertEquals(card, cardInDb);
        assertEquals(folder2.id, cardInDb.folderId);
        assertEquals(cardType1.id, cardInDb.cardTypeId);
        cardHist = db.select(
            CardHistEnt.class, sc.getCardTable().getHistTable(), null, List.of(HIST_ID), null
        );
        cardHistRec0 = cardHist.get(0);
        assertEquals(0, cardHistRec0._act);
        assertEquals(histTime0, cardHistRec0._time);
        assertEquals(card.id, cardHistRec0.id);
        assertEquals(folder1.id, cardHistRec0.folderId);
        assertEquals(cardType1.id, cardHistRec0.cardTypeId);
        assertEquals(card.crtTime, cardHistRec0.crtTime);
        CardHistEnt cardHistRec1 = cardHist.get(1);
        assertEquals(1, cardHistRec1._act);
        Long histTime1 = cardHistRec1._time;
        assertCurrentTime(histTime1);
        assertTrue(histTime0 < histTime1);
        assertEquals(card.id, cardHistRec1.id);
        assertEquals(folder2.id, cardHistRec1.folderId);
        assertEquals(cardType1.id, cardHistRec1.cardTypeId);
        assertEquals(card.crtTime, cardHistRec1.crtTime);

        //when
        //invoke update() without real change in data, no changes in the history table are expected
        db.update(sc.getCardTable(), card);

        //then
        assertEquals(1, countRows(db, sc.getCardTable()));
        assertEquals(2, countRows(db, sc.getCardTable().getHistTable()));

        //when
        //update the second column
        //waiting to change the timestamp in history
        Thread.sleep(10);
        card.cardTypeId = cardType2.id;
        db.update(sc.getCardTable(), card);

        //then
        assertEquals(1, countRows(db, sc.getCardTable()));
        assertEquals(3, countRows(db, sc.getCardTable().getHistTable()));
        cardInDb = db.selectSingleById(CardEnt.class, sc.getCardTable(), card.id);
        assertEquals(card, cardInDb);
        assertEquals(folder2.id, cardInDb.folderId);
        assertEquals(cardType2.id, cardInDb.cardTypeId);
        cardHist = db.select(
            CardHistEnt.class, sc.getCardTable().getHistTable(), null, List.of(HIST_ID), null
        );
        cardHistRec0 = cardHist.get(0);
        assertEquals(0, cardHistRec0._act);
        assertEquals(histTime0, cardHistRec0._time);
        assertEquals(card.id, cardHistRec0.id);
        assertEquals(folder1.id, cardHistRec0.folderId);
        assertEquals(cardType1.id, cardHistRec0.cardTypeId);
        assertEquals(card.crtTime, cardHistRec0.crtTime);
        cardHistRec1 = cardHist.get(1);
        assertEquals(1, cardHistRec1._act);
        assertEquals(histTime1, cardHistRec1._time);
        assertEquals(card.id, cardHistRec1.id);
        assertEquals(folder2.id, cardHistRec1.folderId);
        assertEquals(cardType1.id, cardHistRec1.cardTypeId);
        assertEquals(card.crtTime, cardHistRec1.crtTime);
        CardHistEnt cardHistRec2 = cardHist.get(2);
        assertEquals(1, cardHistRec2._act);
        Long histTime2 = cardHistRec2._time;
        assertCurrentTime(histTime2);
        assertTrue(histTime1 < histTime2);
        assertEquals(card.id, cardHistRec2.id);
        assertEquals(folder2.id, cardHistRec2.folderId);
        assertEquals(cardType2.id, cardHistRec2.cardTypeId);
        assertEquals(card.crtTime, cardHistRec2.crtTime);

        //when
        //delete the card
        //waiting to change the timestamp in history
        Thread.sleep(10);
        db.delete(sc.getCardTable(), card.id);

        //then
        assertEquals(0, countRows(db, sc.getCardTable()));
        assertEquals(4, countRows(db, sc.getCardTable().getHistTable()));
        cardHist = db.select(
            CardHistEnt.class, sc.getCardTable().getHistTable(), null, List.of(HIST_ID), null
        );
        cardHistRec0 = cardHist.get(0);
        assertEquals(0, cardHistRec0._act);
        assertEquals(histTime0, cardHistRec0._time);
        assertEquals(card.id, cardHistRec0.id);
        assertEquals(folder1.id, cardHistRec0.folderId);
        assertEquals(cardType1.id, cardHistRec0.cardTypeId);
        assertEquals(card.crtTime, cardHistRec0.crtTime);
        cardHistRec1 = cardHist.get(1);
        assertEquals(1, cardHistRec1._act);
        assertEquals(histTime1, cardHistRec1._time);
        assertEquals(card.id, cardHistRec1.id);
        assertEquals(folder2.id, cardHistRec1.folderId);
        assertEquals(cardType1.id, cardHistRec1.cardTypeId);
        assertEquals(card.crtTime, cardHistRec1.crtTime);
        cardHistRec2 = cardHist.get(2);
        assertEquals(1, cardHistRec2._act);
        assertEquals(histTime2, cardHistRec2._time);
        assertEquals(card.id, cardHistRec2.id);
        assertEquals(folder2.id, cardHistRec2.folderId);
        assertEquals(cardType2.id, cardHistRec2.cardTypeId);
        assertEquals(card.crtTime, cardHistRec2.crtTime);
        CardHistEnt cardHistRec3 = cardHist.get(3);
        assertEquals(2, cardHistRec3._act);
        Long histTime3 = cardHistRec3._time;
        assertCurrentTime(histTime3);
        assertTrue(histTime2 < histTime3);
        assertEquals(card.id, cardHistRec3.id);
        assertEquals(folder2.id, cardHistRec3.folderId);
        assertEquals(cardType2.id, cardHistRec3.cardTypeId);
        assertEquals(card.crtTime, cardHistRec3.crtTime);
    }

    @Test
    void history_is_written_when_value_changes_from_non_null_to_null() {
        //given
        Database db = DatabaseImpl.getInMemoryDb(null);
        Table testTable = Table.builder()
            .name("test_tbl")
            .columns(List.of(
                Column.builder().name("C1").type(TEXT).notNull(false).build(),
                Column.builder().name("C2").type(TEXT).notNull(false).build()
            ))
            .trackHistory(true)
            .build();
        db.transactionV(tx -> testTable.getSqlText().forEach(tx::execute));
        TestTableEnt row = TestTableEnt.builder().c1("A").c2("B").build();
        db.insert(testTable, row);
        assertEquals(1, countRows(db, testTable.getHistTable()));

        //when
        row.c1 = null;
        db.update(testTable, row);

        //then
        assertEquals(2, countRows(db, testTable.getHistTable()));
    }

    @Test
    void history_is_written_when_value_changes_from_null_to_non_null() {
        //given
        Database db = DatabaseImpl.getInMemoryDb(null);
        Table testTable = Table.builder()
            .name("test_tbl")
            .columns(List.of(
                Column.builder().name("C1").type(TEXT).notNull(false).build(),
                Column.builder().name("C2").type(TEXT).notNull(false).build()
            ))
            .trackHistory(true)
            .build();
        db.transactionV(tx -> testTable.getSqlText().forEach(tx::execute));
        TestTableEnt row = TestTableEnt.builder().c1("A").c2(null).build();
        db.insert(testTable, row);
        assertEquals(1, countRows(db, testTable.getHistTable()));

        //when
        row.c2 = "";
        db.update(testTable, row);

        //then
        assertEquals(2, countRows(db, testTable.getHistTable()));
    }

    @Test
    void history_is_not_written_when_value_doesnt_change() {
        //given
        Database db = DatabaseImpl.getInMemoryDb(null);
        Table testTable = Table.builder()
            .name("test_tbl")
            .columns(List.of(
                Column.builder().name("C1").type(TEXT).notNull(false).build(),
                Column.builder().name("C2").type(TEXT).notNull(false).build()
            ))
            .trackHistory(true)
            .build();
        db.transactionV(tx -> testTable.getSqlText().forEach(tx::execute));
        TestTableEnt row = TestTableEnt.builder().c1("A").c2(null).build();
        db.insert(testTable, row);
        assertEquals(1, countRows(db, testTable.getHistTable()));

        //when
        db.update(testTable, row);

        //then
        assertEquals(1, countRows(db, testTable.getHistTable()));
    }

    @Test
    void insert_checks_foreign_key_constraints() {
        //given
        DbSchema sc = new DbSchemaImpl();
        Database db = DatabaseImpl.getInMemoryDb(sc);
        db.transactionV(sc::upgrade);

        //when
        Exn actualExn = assertThrows(
            Exn.class,
            () -> db.insert(sc.getCardTable(), CardEnt.builder().folderId(17L).cardTypeId(2L).build())
        );

        //then
        assertTrue(actualExn.getCause().getMessage().contains("A foreign key constraint failed"));
    }

    @Test
    void insert_sets_autogenerated_fields() {
        //given
        DbSchema sc = new DbSchemaImpl();
        Database db = DatabaseImpl.getInMemoryDb(sc);
        db.transactionV(sc::upgrade);
        FolderEnt folder = FolderEnt.builder().name("F1").build();
        db.insert(sc.getFolderTable(), folder);
        CardTypeEnt cardType = CardTypeEnt.builder().code("C1").tableName("T2").build();
        db.insert(sc.getCardTypeTable(), cardType);
        CardEnt card = CardEnt.builder().folderId(folder.id).cardTypeId(cardType.id).build();
        assertNull(card.id);
        assertNull(card.crtTime);

        //when
        db.insert(sc.getCardTable(), card);

        //then
        assertEquals(1, card.id);
        assertCurrentTime(card.crtTime);
        CardEnt cardInDb = db.selectSingleById(CardEnt.class, sc.getCardTable(), card.id);
        assertEquals(1, cardInDb.id);
        assertEquals(card.crtTime, cardInDb.crtTime);
    }

    @Test
    void insert_doesnt_override_values_of_autogenerated_fields() {
        //given
        DbSchema sc = new DbSchemaImpl();
        Database db = DatabaseImpl.getInMemoryDb(sc);
        db.transactionV(sc::upgrade);
        FolderEnt folder = FolderEnt.builder().name("F1").build();
        db.insert(sc.getFolderTable(), folder);
        CardTypeEnt cardType = CardTypeEnt.builder().code("C1").tableName("T2").build();
        db.insert(sc.getCardTypeTable(), cardType);
        CardEnt card = CardEnt.builder().folderId(folder.id).cardTypeId(cardType.id).crtTime(-1L).build();
        assertNull(card.id);
        assertEquals(-1L, card.crtTime);

        //when
        db.insert(sc.getCardTable(), card);

        //then
        assertEquals(1, card.id);
        assertEquals(-1L, card.crtTime);
        CardEnt cardInDb = db.selectSingleById(CardEnt.class, sc.getCardTable(), card.id);
        assertEquals(1, cardInDb.id);
        assertEquals(card.crtTime, cardInDb.crtTime);
    }

    private int countRows(Database db, Table table) {
        return (int) db.selectSingle("select count(1) from " + table.getName());
    }

    private void assertCurrentTime(Long millis) {
        long curMillis = Instant.now().toEpochMilli();
        assertTrue(curMillis - 50 <= millis && millis <= curMillis + 50);
    }

    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @EqualsAndHashCode
    private static class TestTableEnt {
        public Long id;
        public String c1;
        public String c2;
    }

}