package org.igye.remem3.utils.sqlite.impl;

import org.igye.remem3.app.db.DbConstants;
import org.igye.remem3.app.db.DbSchema;
import org.igye.remem3.app.db.entities.LangEnt;
import org.igye.remem3.app.db.impl.DbSchemaImpl;
import org.igye.remem3.utils.sqlite.Database;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.List;

class TransactionImplTest {
    @Test
    void insert_sets_autogenerated_ids() {
        //given
        Database db = DatabaseImpl.getInMemoryDb();
        DbSchema sc = new DbSchemaImpl();
        db.transactionV(sc::upgrade);
        List<LangEnt> langs = List.of(
            LangEnt.builder().name("L1").build(),
            LangEnt.builder().name("L2").build(),
            LangEnt.builder().name("L3").build()
        );

        //when
        db.transactionV(tx -> tx.insertMany(sc.getLanguageTable(), langs));

        //then
        Assertions.assertEquals(1, langs.get(0).id);
        Assertions.assertEquals(2, langs.get(1).id);
        Assertions.assertEquals(3, langs.get(2).id);
    }

    @Test
    void selectAll() {
        //given
        Database db = DatabaseImpl.getInMemoryDb();
        DbSchema sc = new DbSchemaImpl();
        db.transactionV(sc::upgrade);
        db.transactionV(tx -> tx.insertMany(
            sc.getLanguageTable(),
            List.of(
                LangEnt.builder().name("L1").build(),
                LangEnt.builder().name("L2").build(),
                LangEnt.builder().name("L3").build()
            )
        ));

        //when
        List<LangEnt> langs = db.transaction(tx ->
            tx.selectAll(sc.getLanguageTable(), LangEnt.class, List.of(DbConstants.LANG_NAME))
        );

        //then
        Assertions.assertEquals(1, langs.get(0).id);
        Assertions.assertEquals(2, langs.get(1).id);
        Assertions.assertEquals(3, langs.get(2).id);
    }
}