package org.igye.remem3.tools.fillgapstotranslateconversion;

import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import org.apache.commons.lang3.StringUtils;
import org.igye.remem3.app.CardUtils;
import org.igye.remem3.app.dto.Card;
import org.igye.remem3.app.dto.fillgaps.TextPart;
import org.igye.remem3.app.impl.CardUtilsImpl;
import org.igye.remem3.utils.Exn;
import org.igye.remem3.utils.impl.UtilsImpl;

import java.io.File;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.stream.Collectors;

import static java.lang.String.format;
import static org.igye.remem3.app.controllers.convertfillgapstotrnaslate.ConvertFillGapsToTranslateController.ATTR_AUTO_GENERATED_FROM;
import static org.igye.remem3.app.controllers.convertfillgapstotrnaslate.ConvertFillGapsToTranslateController.EXISTING_CARD_KEY_PAT;

@RequiredArgsConstructor
public class AddExamplesForAutoGeneratedTranCardsMain {
    private final CardUtils cardUtils;

    public static void main(String[] args) {
        new AddExamplesForAutoGeneratedTranCardsMain(new CardUtilsImpl(new UtilsImpl(new ObjectMapper()), null)).run(args[0]);
    }

    private void run(String dirWithCards) {
        Map<String, String> fileNameToExample = cardUtils.loadAllCards(new File(dirWithCards)).stream()
            .filter(c -> c instanceof Card.FillGaps)
            .map(Card.FillGaps.class::cast)
            .collect(Collectors.toMap(
                c -> c.getFile().get().getName(),
                c -> c.getText().stream()
                    .map(tp -> {
                        if (tp instanceof TextPart.Text) {
                            return ((TextPart.Text) tp).getText();
                        } else {
                            return ((TextPart.Gap) tp).getAnswer();
                        }
                    })
                    .collect(Collectors.joining(" "))
            ));
        cardUtils.loadAllCards(new File(dirWithCards)).stream()
            .filter(c -> c instanceof Card.Translate)
            .map(Card.Translate.class::cast)
            .filter(c -> StringUtils.isBlank(c.getExample1()))
            .filter(c -> c.getAttrs().containsKey(ATTR_AUTO_GENERATED_FROM))
            .filter(c -> EXISTING_CARD_KEY_PAT.matcher(c.getAttrs().get(ATTR_AUTO_GENERATED_FROM)).matches())
            .forEach(c -> {
                Matcher matcher = EXISTING_CARD_KEY_PAT.matcher(c.getAttrs().get(ATTR_AUTO_GENERATED_FROM));
                if (!matcher.find()) {
                    throw new Exn(format("!matcher.find() in '%s'", c.getNotes()));
                }
                String fileName = matcher.group(1);
                if (fileNameToExample.containsKey(fileName)) {
                    c.setExample1(fileNameToExample.get(fileName));
                    cardUtils.saveCard(c.getFile().get(), c);
                }
            });
    }
}
