package org.igye.remem3.tools.fillgapstotranslateconversion;

import lombok.RequiredArgsConstructor;
import org.igye.remem3.app.CardUtils;
import org.igye.remem3.app.dto.Card;
import org.igye.remem3.app.impl.CardUtilsImpl;
import org.igye.remem3.utils.Exn;
import org.igye.remem3.utils.impl.UtilsImpl;
import tools.jackson.databind.ObjectMapper;

import java.io.File;
import java.util.regex.Matcher;

import static java.lang.String.format;
import static org.igye.remem3.app.controllers.convertfillgapstotrnaslate.ConvertFillGapsToTranslateController.ATTR_AUTO_GENERATED_FROM;
import static org.igye.remem3.app.controllers.convertfillgapstotrnaslate.ConvertFillGapsToTranslateController.EXISTING_CARD_KEY_PAT;

@RequiredArgsConstructor
public class MoveAutoGeneratedToAttrsMain {
    private final CardUtils cardUtils;

    public static void main(String[] args) {
        new MoveAutoGeneratedToAttrsMain(new CardUtilsImpl(new UtilsImpl(new ObjectMapper()), null)).run(args[0]);
    }

    private void run(String dirWithCards) {
        cardUtils.loadAllCards(new File(dirWithCards)).stream()
            .filter(c -> c instanceof Card.Translate)
            .map(Card.Translate.class::cast)
            .filter(c -> EXISTING_CARD_KEY_PAT.matcher(c.getNotes()).find())
            .forEach(c -> {
                Matcher matcher = EXISTING_CARD_KEY_PAT.matcher(c.getNotes());
                if (!matcher.find()) {
                    throw new Exn(format("!matcher.find() in '%s'", c.getNotes()));
                }
                c.getAttrs().put(
                    ATTR_AUTO_GENERATED_FROM,
                    format("%s:%s", matcher.group(1).trim(), matcher.group(2).trim())
                );
                c.setNotes(c.getNotes().replaceAll(EXISTING_CARD_KEY_PAT.pattern(), "").trim());
                cardUtils.saveCard(c.getFile().get(), c);
            });
    }
}
